package main;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.List;
import java.io.IOException;
import java.lang.reflect.Array;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author GAME
 */
public class Finished extends javax.swing.JDialog {

    String returnString = "";
    FullScreen j;

    /**
     * Creates new form test
     */
    public Finished(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.j = (FullScreen) parent;
        initComponents();
        this.getContentPane().setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
        this.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(this);
        jLabel5.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\finished.png"));
        jLabel4.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\continue.png"));

        jLabel6.setLayout(new BoxLayout(jLabel6, BoxLayout.LINE_AXIS));

        jLabel6.setHorizontalAlignment(SwingConstants.CENTER);

        JLabel score = new JLabel();
        score.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\score.png"));
        jLabel6.add(score);

        int number = j.tCount; // = and int
        if (number > 0) {
            LinkedList<Integer> stack = new LinkedList<Integer>();
            while (number > 0) {
                stack.push(number % 10);
                number = number / 10;
            }
            while (!stack.isEmpty()) {
                JLabel icon1Label = new JLabel();
                icon1Label.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\" + stack.pop() + ".png"));

                jLabel6.add(icon1Label);
            }
        } else {
            JLabel icon1Label = new JLabel();
            icon1Label.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\0.png"));
            jLabel6.add(icon1Label);
        }
        jLabel6.setHorizontalTextPosition(JLabel.LEFT);
        j.gameRunning = false;

        try {
            saveData();
        } catch (IOException ex) {
            Logger.getLogger(Finished.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 280, 50));

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getSize()-8f));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 380, 50));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private static final String NEW_LINE = System.lineSeparator();

    public void getIcon(int pos) {

    }

    private void saveData() throws IOException {

        Path path = Paths.get("F:\\Apps\\YEET\\src\\main\\java\\resources\\settingsFile.txt");
        appendToFile(path, "Score: " + j.tCount + "  Time: " + j.gTime + "  Targets: " + j.gTarget + NEW_LINE);
    }

    private static void appendToFile(Path path, String content)
            throws IOException {

        // if file not exists throws java.nio.file.NoSuchFileException
        /* Files.write(path, content.getBytes(StandardCharsets.UTF_8),
                        StandardOpenOption.APPEND);*/
        // if file not exists, create and write to it
        // otherwise append to the end of the file
        Files.write(path, content.getBytes(StandardCharsets.UTF_8),
                StandardOpenOption.CREATE,
                StandardOpenOption.APPEND);

    }
    AudioPlayerExample1 player;

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\continue2.png"));
        player = new AudioPlayerExample1();
        player.setLabel(jLabel4);
        player.setImg("F:\\Apps\\YEET\\src\\main\\java\\resources\\continue2.png");
        player.play("F:\\Apps\\YEET\\src\\main\\java\\resources\\select.wav");
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\continue.png"));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:

        returnString = "f";
        j.setReturnString("f");
        j.setDispose(true);
        j.returnPaused(this);
        j.getjProgressBar1().setValue(0);

        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        player = new AudioPlayerExample1();
        player.play("F:\\Apps\\YEET\\src\\main\\java\\resources\\finished.wav");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pause.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pause.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pause.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pause.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pause dialog = new Pause(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
