/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author GAME
 */
public class YesNo extends javax.swing.JDialog {

    FullScreen option;
    MainMenu option1;
    Frame parent1;

    /**
     * Creates new form NewJDialog
     */
    public YesNo(java.awt.Frame parent, boolean modal, String mode) {
        super(parent, modal);
        this.parent1 = parent;
        if (parent.getTitle() == "Your Easy Eye Training") {
            option1 = (MainMenu) parent;
            initComponents();

            jLabel1.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\yes.png"));
            jLabel2.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\no.png"));

            if (mode == "quit") {
                jLabel3.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\option.png"));
                this.setTitle("Select An Option...");
            } else if (mode == "restart") {
                jLabel3.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\optionr.png"));
                this.setTitle("Select An Option...");
            } else if (mode == "stop") {
                jLabel3.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\options.png"));
                this.setTitle("Select An Option...");
            }

            this.getContentPane().setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
            this.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            this.setLocationRelativeTo(this);
        } else {
            option = (FullScreen) parent;
            initComponents();

            jLabel1.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\yes.png"));
            jLabel2.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\no.png"));

            if (mode == "quit") {
                jLabel3.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\option.png"));
                this.setTitle("Select An Option...");
            } else if (mode == "restart") {
                jLabel3.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\optionr.png"));
                this.setTitle("Select An Option...");
            } else if (mode == "stop") {
                jLabel3.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\options.png"));
                this.setTitle("Select An Option...");
            }

            this.getContentPane().setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
            this.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            this.setLocationRelativeTo(this);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 70, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 70, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if (parent1.getTitle() == "Your Easy Eye Training") {
            option1.input = 0;
        } else {
            option.input = 0;
        }
        this.dispose();

    }//GEN-LAST:event_jLabel1MouseClicked

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
            if (parent1.getTitle() == "Your Easy Eye Training") {
            option1.input = 1;
        } else {
            option.input = 1;
        }
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked
    AudioPlayerExample1 player;
    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\yes2.png"));

        player = new AudioPlayerExample1();
        player.setLabel(jLabel1);
        player.setImg("F:\\Apps\\YEET\\src\\main\\java\\resources\\yes2.png");
        player.play("F:\\Apps\\YEET\\src\\main\\java\\resources\\select.wav");

    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\yes.png"));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel2.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\no2.png"));

        player = new AudioPlayerExample1();
        player.setLabel(jLabel2);
        player.setImg("F:\\Apps\\YEET\\src\\main\\java\\resources\\no2.png");
        player.play("F:\\Apps\\YEET\\src\\main\\java\\resources\\select.wav");
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:

        jLabel2.setIcon(new ImageIcon("F:\\Apps\\YEET\\src\\main\\java\\resources\\no.png"));
    }//GEN-LAST:event_jLabel2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YesNo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YesNo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YesNo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YesNo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
